### ISSUE TITLE
Channel Join Request REST API

### ISSUE THREAD

**Issue by Techbhatia** [Groupease/groupease#22]
Channel Join Request REST endpoint 
Includes:
List
Get
Create
Accept
Reject
Delete

**Comment by mckoon** [comment]
"Rest API" - This ticket is really vague. Specifically what is this ticket to track?
I think it would be better to specify which object: "Group Invitation REST API" so we know what this ticket is for, and others can grab other objects without worry of stepping on each others toes.

**Comment by Techbhatia** [comment]
I agree.
